
title : personal web - Pranjal Gupta
description : space to know all about my projects, work and ideas...
keywords : pranjal gupta, inarena, g31pranjal, pranjal's blog
domain : 139.59.16.166

timezone : Asia/Kolkata

exclude : ["Gemfile", "Gemfile.lock", "README.md"]

collections :
  projects :
    output : true 
