
title : personal web - Pranjal Gupta
description : portfolio 
keywords : pranjal gupta, inarena, g31pranjal, pranjal's blog, bits pilani, uwaterloo
domain : "g31pranjal.xyz"

timezone : Asia/Kolkata

exclude : ["Gemfile", "Gemfile.lock", "README.md"]

collections :
  projects :
    output : true 
  work :
    output : true